### ISSUE TITLE
Correction de quelques typos

### ISSUE THREAD

**Issue by entwanne** [ArnaudCalmettes/cours-python3#6]
J'ai commencé la lecture du contenu actuel, et n'ai pour l'instant parcouru que les deux premiers chapitres.
Cependant, j'ai relevé quelques erreurs de typographie dans le premier. Un commit et une pull-request juste pour ces corrections me paraissait lourd, alors j'ai simplement fait un patch, je ne sais pas ce que tu préfères, mais je laisse ça ici au cas où.

https://gist.github.com/entwanne/1ae50d8da86e076fa98f

**Comment by entwanne** [comment]
Je mets à jour suite à la lecture du reste du tutoriel:
https://gist.github.com/entwanne/aa2f0053c76d899ce72f

**Comment by ArnaudCalmettes** [comment]
Merci !

Du mon côté, j'ai une petite préférence pour les pull-requests parce qu'on peut les merger en un clic, mais un patch ça fera aussi l'affaire. :)

**Comment by ArnaudCalmettes** [comment]
Merged.
